name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller yfinance pandas numpy ta openpyxl
        
    - name: Build executable
      run: |
        pyinstaller main.spec
        
    - name: Clean up old artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
        name: AnalisisMercados
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnalisisMercados
        path: dist/AnalisisMercados.exe
        compression-level: 9
        retention-days: 7 